apiVersion: v1
kind: Service
metadata:
    name: core-backend-service
    
spec:
    type: NodePort
    ports:
       - port: 80
         nodePort: 30002
         targetPort: 80
    selector:
         app: core-backend
         type: netcoreapp