apiVersion: v1
kind: Service
metadata:
    name: core-front-service
    
spec:
    type: NodePort
    ports:
       - port: 80
         nodePort: 30001
    selector:
         app: core-front
         type: angularapp